##### Step 1: Understand the columns
##### step 2: Investigating the mising data
##### step 3: Check your date column
##### step 4: Check for invalid values
##### step 5: Check for unique values
##### step 6: Check ID
##### step 7: Mini Analysis

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:\\Users\\dines\\OneDrive\\Desktop\\Global_superstore_project\\dataset\\Global_Superstore2.csv' , encoding='latin1')

In [ ]:
df.shape

(51290, 24)

In [ ]:
df.columns.to_list()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'City',
 'State',
 'Country',
 'Postal Code',
 'Market',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Cost',
 'Order Priority']

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [ ]:
pd.set_option('display.max_columns',24)

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,US,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,NaN,APAC,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,NaN,APAC,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,NaN,EU,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,NaN,Africa,Africa,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [ ]:
pd.set_option('display.max_rows',24)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [ ]:
df.isna().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Segment']

0           Consumer
1          Corporate
2           Consumer
3        Home Office
4           Consumer
            ...
51285      Corporate
51286       Consumer
51287    Home Office
51288    Home Office
51289       Consumer
Name: Segment, Length: 51290, dtype: str

In [ ]:
df[df['Postal Code'].isna()][['Country','City','State','Postal Code']].head(25)

               Country           City            State  Postal Code
1            Australia     Wollongong  New South Wales          NaN
2            Australia       Brisbane       Queensland          NaN
3              Germany         Berlin           Berlin          NaN
4              Senegal          Dakar            Dakar          NaN
5            Australia         Sydney  New South Wales          NaN
..                 ...            ...              ...          ...
26              Taiwan         Taipei      Taipei City          NaN
27             Germany        Leipzig           Saxony          NaN
29               India          Surat          Gujarat          NaN
30  Dominican Republic  Santo Domingo    Santo Domingo          NaN
31              France   Saint-Brieuc         Brittany          NaN

[25 rows x 4 columns]

In [ ]:
df[df['Postal Code'].isna()][['Country']].value_counts()

Country
Australia      2837
France         2827
Mexico         2644
Germany        2065
China          1880
               ...
South Sudan       2
Bahrain           2
Swaziland         2
Burundi           2
Eritrea           2
Name: count, Length: 146, dtype: int64

In [ ]:
df[df['Postal Code'].notna()]['Country'].head(20)

0     United States
8     United States
9     United States
10    United States
16    United States
21    United States
28    United States
32    United States
34    United States
36    United States
37    United States
45    United States
50    United States
52    United States
56    United States
59    United States
61    United States
65    United States
76    United States
82    United States
Name: Country, dtype: str

In [ ]:
df[df['Postal Code'].notna()]['Country'].value_counts()

Country
United States    9994
Name: count, dtype: int64

In [ ]:
print(df['Order Date'].head(20))
print(df['Ship Date'].head(20))

0     31-07-2012
1     05-02-2013
2     17-10-2013
3     28-01-2013
4     05-11-2013
5     28-06-2013
6     07-11-2011
7     14-04-2012
8     14-10-2014
9     28-01-2012
10    05-04-2011
11    19-04-2012
12    27-12-2011
13    13-11-2012
14    06-06-2013
15    31-07-2014
16    03-11-2014
17    08-09-2014
18    31-01-2014
19    05-12-2014
Name: Order Date, dtype: str
0     31-07-2012
1     07-02-2013
2     18-10-2013
3     30-01-2013
4     06-11-2013
5     01-07-2013
6     09-11-2011
7     18-04-2012
8     21-10-2014
9     31-01-2012
10    09-04-2011
11    22-04-2012
12    29-12-2011
13    13-11-2012
14    08-06-2013
15    03-08-2014
16    06-11-2014
17    14-09-2014
18    01-02-2014
19    07-12-2014
Name: Ship Date, dtype: str

In [ ]:
df['Order Date']=pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date']=pd.to_datetime(df['Ship Date'], dayfirst=True)

In [ ]:
df[['Order Date','Ship Date']].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [ ]:
df_2013 = df[df['Order Date'].dt.year == 2013]

In [ ]:
df_2013

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,NaN,APAC,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,NaN,APAC,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,NaN,EU,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,NaN,Africa,Africa,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2013-42360,2013-06-28,2013-07-01,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,Australia,NaN,APAC,Oceania,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51259,39396,CA-2013-169663,2013-03-11,2013-03-14,First Class,RH-19510,Rick Huthwaite,Home Office,Los Angeles,California,United States,90045.0,US,West,TEC-AC-10003038,Technology,Accessories,Kingston Digital DataTraveler 16GB USB 2.0,26.850,3,0.0,5.1015,0.04,Medium
51260,40079,CA-2013-116911,2013-09-16,2013-09-21,Standard Class,JD-16150,Justin Deggeller,Corporate,Twin Falls,Idaho,United States,83301.0,US,West,OFF-BI-10001249,Office Supplies,Binders,Avery Heavy-Duty EZD View Binder with Locking ...,20.416,4,0.2,6.6352,0.04,Medium
51269,36834,US-2013-167472,2013-06-07,2013-06-08,First Class,CK-12595,Clytie Kelty,Consumer,Little Rock,Arkansas,United States,72209.0,US,South,OFF-PA-10001534,Office Supplies,Paper,Xerox 230,12.960,2,0.0,6.2208,0.03,High
51273,5596,MX-2013-134600,2013-09-30,2013-10-02,Second Class,SS-20410,Shahid Shariari,Consumer,Acayucan,Veracruz,Mexico,NaN,LATAM,North,OFF-BI-10002414,Office Supplies,Binders,"Ibico Index Tab, Economy",41.640,6,0.0,3.7200,0.02,High
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,United States,93030.0,US,West,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.01,High

In [ ]:
df[['Sales','Quantity','Discount','Profit','Shipping Cost']].describe()

              Sales      Quantity      Discount        Profit  Shipping Cost
count  51290.000000  51290.000000  51290.000000  51290.000000   51290.000000
mean     246.490581      3.476545      0.142908     28.610982      26.375915
std      487.565361      2.278766      0.212280    174.340972      57.296804
min        0.444000      1.000000      0.000000  -6599.978000       0.000000
25%       30.758625      2.000000      0.000000      0.000000       2.610000
50%       85.053000      3.000000      0.000000      9.240000       7.790000
75%      251.053200      5.000000      0.200000     36.810000      24.450000
max    22638.480000     14.000000      0.850000   8399.976000     933.570000

In [ ]:
print('Negative sales:', (df['Sales']<0).sum())
print('Negative Quantity:', (df['Quantity']<0).sum())
print('Negative Discount:', (df['Discount']<0).sum())

Negative sales: 0
Negative Quantity: 0
Negative Discount: 0

In [ ]:
print('Categories:', df['Category'].unique())
print('Segments:', df['Segment'].unique())
print('Shipping Methods:', df['Ship Mode'].unique())
print('Order Priorities:', df['Order Priority'].unique())
print('Markets  :', df['Market'].unique())
print('Regions  :', df['Region'].unique())

Categories: <StringArray>
['Technology', 'Furniture', 'Office Supplies']
Length: 3, dtype: str
Segments: <StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str
Shipping Methods: <StringArray>
['Same Day', 'Second Class', 'First Class', 'Standard Class']
Length: 4, dtype: str
Order Priorities: <StringArray>
['Critical', 'Medium', 'High', 'Low']
Length: 4, dtype: str
Markets  : <StringArray>
['US', 'APAC', 'EU', 'Africa', 'EMEA', 'LATAM', 'Canada']
Length: 7, dtype: str
Regions  : <StringArray>
[          'East',        'Oceania',        'Central',         'Africa',
           'West',          'South',   'Central Asia',           'EMEA',
     'North Asia',          'North',      'Caribbean', 'Southeast Asia',
         'Canada']
Length: 13, dtype: str

In [ ]:
print('Rows :', len(df))
print('Unique Rows :', df['Row ID'].nunique())
print('Orders :', df['Order ID'].nunique())
print('Customers :', df['Customer ID'].nunique())
print('Products :', df['Product ID'].nunique())

Rows : 51290
Unique Rows : 51290
Orders : 25035
Customers : 1590
Products : 10292

In [ ]:
print('Total profit:', df['Profit'].sum())
print('Total sales:', df['Sales'].sum())
print('Total quantity:', df['Quantity'].sum())

Total profit: 1467457.29128
Total sales: 12642501.90988
Total quantity: 178312

In [ ]:
print(df.groupby('Category')['Sales'].sum().sort_values(ascending=False))
print(df.groupby('Category')['Profit'].sum().sort_values(ascending=False))

Category
Technology         4.744557e+06
Furniture          4.110874e+06
Office Supplies    3.787070e+06
Name: Sales, dtype: float64
Category
Technology         663778.73318
Office Supplies    518473.83430
Furniture          285204.72380
Name: Profit, dtype: float64

In [ ]:
print(df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False))

Product Name
Apple Smart Phone, Full Size                                        86935.7786
Cisco Smart Phone, Full Size                                        76441.5306
Motorola Smart Phone, Full Size                                     73156.3030
Nokia Smart Phone, Full Size                                        71904.5555
Canon imageCLASS 2200 Advanced Copier                               61599.8240
                                                                       ...
Avery Hi-Liter Pen Style Six-Color Fluorescent Set                      7.7000
Grip Seal Envelopes                                                     7.0720
Xerox 20                                                                6.4800
Avery 5                                                                 5.7600
Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac        1.6240
Name: Sales, Length: 3788, dtype: float64

In [ ]:
print(df.groupby('Product Name')['Profit'].sum().sort_values(ascending=False))

Product Name
Canon imageCLASS 2200 Advanced Copier        25199.9280
Cisco Smart Phone, Full Size                 17238.5206
Motorola Smart Phone, Full Size              17027.1130
Hoover Stove, Red                            11807.9690
Sauder Classic Bookcase, Traditional         10672.0730
                                                ...
Bevis Round Table, Adjustable Height         -3649.8940
Cubify CubeX 3D Printer Triple Head Print    -3839.9904
Motorola Smart Phone, Cordless               -4447.0380
Lexmark MX611dhe Monochrome Laser Printer    -4589.9730
Cubify CubeX 3D Printer Double Head Print    -8879.9704
Name: Profit, Length: 3788, dtype: float64

##### Step 8: Check datatypes 
##### Step 9: Checking if Data is valid or invalid
##### Step 10: Checking the missing values again
##### Step 11: Checking if IDs are correct

In [ ]:
df.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Segment                      str
City                         str
State                        str
Country                      str
Postal Code              float64
Market                       str
Region                       str
Product ID                   str
Category                     str
Sub-Category                 str
Product Name                 str
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority               str
dtype: object

In [ ]:
(df['Ship Date'] < df['Order Date']).sum()

np.int64(0)

In [ ]:
df[df['Ship Date'] < df['Order Date']][['Order ID','Order Date','Ship Date']].head(20)

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date]
Index: []

In [ ]:
problem_data = df[df['Ship Date'] < df['Order Date']]
problem_data[['Order ID','Order Date','Ship Date']]

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date]
Index: []

In [ ]:
print(len(problem_data))

0

In [ ]:
df['Valid_date'] = df['Ship Date'] >= df['Order Date']

In [ ]:
df['Valid_date'].value_counts()

Valid_date
True    51290
Name: count, dtype: int64

In [ ]:
pd.set_option('display.max_rows', None)

df.isna().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
Valid_date            0
dtype: int64

In [ ]:
df[df.isna().any(axis=1)].head(20)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Valid_date
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,NaN,...,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.765,923.63,Critical,True
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,NaN,...,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.971,915.49,Medium,True
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,NaN,...,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.540,910.16,Medium,True
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,NaN,...,Africa,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.520,903.04,Critical,True
5,22732,IN-2013-42360,2013-06-28,2013-07-01,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,Australia,NaN,...,Oceania,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.275,897.35,Critical,True
6,30570,IN-2011-81826,2011-11-07,2011-11-09,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,New Zealand,NaN,...,Oceania,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.840,894.77,Critical,True
7,31192,IN-2012-86369,2012-04-14,2012-04-18,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,New Zealand,NaN,...,Oceania,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.480,878.38,High,True
11,28879,ID-2012-28402,2012-04-19,2012-04-22,First Class,AJ-10780,Anthony Jacobs,Corporate,Kabul,Kabul,Afghanistan,NaN,...,Central Asia,FUR-TA-10001889,Furniture,Tables,"Bevis Conference Table, Fully Assembled",4626.150,5,0.0,647.550,835.57,High,True
12,45794,SA-2011-1830,2011-12-27,2011-12-29,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,Saudi Arabia,NaN,...,EMEA,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.960,4,0.0,1151.400,832.41,Critical,True
13,4132,MX-2012-130015,2012-11-13,2012-11-13,Same Day,VF-21715,Vicky Freymann,Home Office,Toledo,Parana,Brazil,NaN,...,South,FUR-CH-10002033,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",2221.800,7,0.0,622.020,810.25,Critical,True
14,27704,IN-2013-73951,2013-06-06,2013-06-08,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,China,NaN,...,North Asia,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.520,12,0.0,1036.080,804.54,Critical,True
15,13779,ES-2014-5099955,2014-07-31,2014-08-03,Second Class,BP-11185,Ben Peterman,Corporate,Paris,Ile-de-France,France,NaN,...,Central,OFF-AP-10000423,Office Supplies,Appliances,"Breville Refrigerator, Red",1869.588,4,0.1,186.948,801.66,Critical,True
17,12069,ES-2014-1651774,2014-09-08,2014-09-14,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,Italy,NaN,...,South,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",7958.580,14,0.0,3979.080,778.32,Low,True
18,22096,IN-2014-11763,2014-01-31,2014-02-01,First Class,JS-15685,Jim Sink,Corporate,Townsville,Queensland,Australia,NaN,...,Oceania,TEC-CO-10000865,Technology,Copiers,"Brother Fax Machine, High-Speed",2565.594,9,0.1,28.404,766.93,Critical,True
19,49463,TZ-2014-8190,2014-12-05,2014-12-07,Second Class,RH-9555,Ritsa Hightower,Consumer,Uvinza,Kigoma,Tanzania,NaN,...,Africa,OFF-KIT-10004058,Office Supplies,Appliances,"KitchenAid Stove, White",3409.740,6,0.0,818.280,763.38,High,True
20,46630,PL-2012-7820,2012-08-08,2012-08-10,First Class,AB-600,Ann Blume,Corporate,Bytom,Silesia,Poland,NaN,...,EMEA,FUR-HON-10000224,Furniture,Tables,"Hon Computer Table, with Bottom Storage",1977.720,4,0.0,276.840,759.47,Critical,True
22,21586,IN-2011-44803,2011-05-02,2011-05-03,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,China,NaN,...,North Asia,FUR-CH-10000027,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",2754.000,6,0.0,358.020,752.47,Critical,True
23,13528,ES-2013-2860574,2013-02-27,2013-03-01,Second Class,LB-16795,Laurel Beltran,Home Office,Edinburgh,Scotland,United Kingdom,NaN,...,North,OFF-AP-10003590,Office Supplies,Appliances,"KitchenAid Refrigerator, Black",5273.700,10,0.0,1898.400,730.91,High,True
24,1570,US-2014-133193,2014-07-31,2014-08-01,First Class,NP-18325,Naresj Patel,Consumer,Juárez,Chihuahua,Mexico,NaN,...,North,TEC-PH-10004182,Technology,Phones,"Motorola Smart Phone, Full Size",1713.840,4,0.0,445.520,728.97,Critical,True
25,3484,MX-2014-165309,2014-09-05,2014-09-08,First Class,VD-21670,Valerie Dominguez,Consumer,Soyapango,San Salvador,El Salvador,NaN,...,Central,FUR-TA-10002827,Furniture,Tables,"Hon Computer Table, Fully Assembled",2106.496,8,0.2,526.496,728.39,Critical,True

In [ ]:
df['Order ID'].value_counts().head(20)

Order ID
CA-2014-100111     14
IN-2013-42311      13
MX-2014-166541     13
IN-2012-41261      13
NI-2014-8880       13
TO-2014-9950       13
CA-2014-157987     12
IN-2014-15263      12
IN-2011-76625      12
ES-2012-5776825    12
MX-2013-127705     12
MX-2013-142678     12
ES-2014-4673578    11
SF-2014-3260       11
CA-2013-165330     11
IN-2013-78809      11
ES-2014-5605089    11
SA-2013-7790       11
US-2013-108504     11
ES-2013-2700361    11
Name: count, dtype: int64

In [ ]:
df['Product ID'].value_counts().head(20)

Product ID
OFF-AR-10003651     35
OFF-AR-10003829     31
OFF-BI-10002799     30
OFF-BI-10003708     30
FUR-CH-10003354     28
OFF-BI-10002570     27
OFF-BI-10004140     25
OFF-BI-10003650     24
OFF-BI-10004632     24
OFF-BI-10001808     24
OFF-BI-10004195     24
OFF-AR-10000091     23
OFF-BIN-10002061    23
OFF-BI-10000542     23
OFF-AR-10004825     22
OFF-AR-10000110     22
OFF-BI-10004654     22
OFF-STA-10001791    22
OFF-BI-10001249     22
OFF-STA-10001747    21
Name: count, dtype: int64

In [ ]:
df.groupby('Product ID')['Product Name'].nunique().sort_values(ascending=False).head(10)

Product ID
OFF-PA-10004673    4
OFF-BI-10004632    3
FUR-FU-10004960    3
OFF-BI-10003708    3
OFF-EN-10003737    3
OFF-BI-10002799    3
FUR-CH-10002335    3
FUR-FU-10001933    3
OFF-AR-10000833    3
OFF-BI-10004654    3
Name: Product Name, dtype: int64

In [ ]:
df[['Product Name', 'Product ID']].head(10)

                                        Product Name        Product ID
0  Plantronics CS510 - Over-the-Head monaural Wir...   TEC-AC-10003033
1          Novimex Executive Leather Armchair, Black   FUR-CH-10003950
2                  Nokia Smart Phone, with Caller ID   TEC-PH-10004664
3                     Motorola Smart Phone, Cordless   TEC-PH-10004583
4                     Sharp Wireless Fax, High-Speed  TEC-SHA-10000501
5                Samsung Smart Phone, with Caller ID   TEC-PH-10000030
6     Novimex Executive Leather Armchair, Adjustable   FUR-CH-10004050
7       Chromcraft Conference Table, Fully Assembled   FUR-TA-10002958
8  Fellowes PB500 Electric Punch Plastic Comb Bin...   OFF-BI-10003527
9  Chromcraft Bull-Nose Wood Oval Conference Tabl...   FUR-TA-10000198

In [ ]:
df['Customer ID'].value_counts().head(10)

Customer ID
PO-18850    97
BE-11335    94
JG-15805    90
SW-20755    89
MY-18295    85
EM-13960    85
ZC-21910    84
MP-17965    84
CK-12205    83
BW-11110    81
Name: count, dtype: int64

In [ ]:
df.groupby('Customer ID')['Customer Name'].nunique().sort_values(ascending=False).head(10)

Customer ID
AA-10315    1
AA-10375    1
AA-10480    1
AA-10645    1
AA-315      1
AA-375      1
AA-480      1
AA-645      1
AB-10015    1
AB-10060    1
Name: Customer Name, dtype: int64

##### Step 12: Cleaning missing Data

In [ ]:
Invalid_dates = (df['Valid_date'] == False).sum()
print('Number of invalid dates:', Invalid_dates)

Number of invalid dates: 0

In [ ]:
df = df[df['Valid_date'] == True].copy()

In [ ]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Valid_date
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,10024.0,...,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical,True
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,NaN,...,Oceania,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical,True
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,NaN,...,Oceania,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium,True
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,NaN,...,Central,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium,True
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,NaN,...,Africa,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical,True
5,22732,IN-2013-42360,2013-06-28,2013-07-01,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,Australia,NaN,...,Oceania,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical,True
6,30570,IN-2011-81826,2011-11-07,2011-11-09,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,New Zealand,NaN,...,Oceania,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical,True
7,31192,IN-2012-86369,2012-04-14,2012-04-18,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,New Zealand,NaN,...,Oceania,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High,True
8,40155,CA-2014-135909,2014-10-14,2014-10-21,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,United States,95823.0,...,West,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.960,5,0.2,1906.4850,867.69,Low,True
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,United States,28027.0,...,South,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.644,13,0.4,-1862.3124,865.74,Critical,True

In [ ]:
df.drop(columns=['Valid_date'], inplace=True)

In [ ]:
print((df['Ship Date'] < df['Order Date']).sum())

0

##### step 13: Clean the column names

In [ ]:
df.columns=(df.columns
            .str.strip()
            .str.lower()
            .str.replace(' ', '_')
            )

In [ ]:
df.columns.to_list()

['row_id',
 'order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_id',
 'customer_name',
 'segment',
 'city',
 'state',
 'country',
 'postal_code',
 'market',
 'region',
 'product_id',
 'category',
 'sub-category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'shipping_cost',
 'order_priority']

##### step 14: Handling null values (skipped in pandas. will hanlde in sql and snowflake)
##### step 15: Check duplcate rows again
##### Step 16: Again validate the important numberical columns

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

row_id                     int64
order_id                     str
order_date        datetime64[us]
ship_date         datetime64[us]
ship_mode                    str
customer_id                  str
customer_name                str
segment                      str
city                         str
state                        str
country                      str
postal_code              float64
market                       str
region                       str
product_id                   str
category                     str
sub-category                 str
product_name                 str
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority               str
dtype: object

In [ ]:
print(df[['sales','quantity','discount','profit','shipping_cost']].describe())

              sales      quantity      discount        profit  shipping_cost
count  51290.000000  51290.000000  51290.000000  51290.000000   51290.000000
mean     246.490581      3.476545      0.142908     28.610982      26.375915
std      487.565361      2.278766      0.212280    174.340972      57.296804
min        0.444000      1.000000      0.000000  -6599.978000       0.000000
25%       30.758625      2.000000      0.000000      0.000000       2.610000
50%       85.053000      3.000000      0.000000      9.240000       7.790000
75%      251.053200      5.000000      0.200000     36.810000      24.450000
max    22638.480000     14.000000      0.850000   8399.976000     933.570000

In [ ]:
print('Negative_sales: ', (df['sales']<0).sum())
print('Negative_quantity: ', (df['quantity']<0).sum())
print('Negative_discount: ', (df['discount']<0).sum())
print('Negative_profit: ', (df['profit']<0).sum())
print('Negative_shipping_cost: ', (df['shipping_cost']<0).sum())

Negative_sales:  0
Negative_quantity:  0
Negative_discount:  0
Negative_profit:  12544
Negative_shipping_cost:  0

In [ ]:
for col in df.select_dtypes(include=['object']).columns:
    print(col, (df[col].astype('str').str.strip()=='').sum())

order_id 0
ship_mode 0
customer_id 0
customer_name 0
segment 0
city 0
state 0
country 0
market 0
region 0
product_id 0
category 0
sub-category 0
product_name 0
order_priority 0

C:\Users\dines\AppData\Local\Temp\ipykernel_14060\596931416.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

In [ ]:
print('Rows :', len(df))
print('Columns :', len(df.columns))
print('Duplicates :', df.duplicated().sum())
print('Missing values :', df.isnull().sum())

Rows : 51290
Columns : 24
Duplicates : 0
Missing values : row_id                0
order_id              0
order_date            0
ship_date             0
ship_mode             0
customer_id           0
customer_name         0
segment               0
city                  0
state                 0
country               0
postal_code       41296
market                0
region                0
product_id            0
category              0
sub-category          0
product_name          0
sales                 0
quantity              0
discount              0
profit                0
shipping_cost         0
order_priority        0
dtype: int64

In [ ]:
df.to_csv('C:\\Users\\dines\\OneDrive\\Desktop\\Global_superstore_project\\dataset\\Global_Superstore_cleaned.csv', index=False)

In [ ]:
df.shape

(51290, 24)

In [ ]:
print((df['Ship Date'] < df['Order Date']).sum())

NameError: name 'df' is not defined